### ISSUE TITLE
Error-Code: 106-1202

### ISSUE THREAD

**Issue by MiiCordYT** [SmmServer/SmmServer#4]
![errir](https://user-images.githubusercontent.com/35873344/68554833-9b453c00-03f8-11ea-9ba4-db9f50b5573e.png)

So I'm trying to access 100 Mario with SMMServer but everytime I try, I get this error. I have the european copy, I have V272, I'm running Debugview and I'm still getting this error! If anyone could figure out what I'm missing that would be great! Thanks!

**Comment by mrexodia** [comment]
Could you post the log files next to SmmServer.exe? Also how did you configure Cemu? You have to use a clean installation (do not change the MLC path and install the SMM update from scratch).

**Comment by MiiCordYT** [comment]
[Caddy.log](https://github.com/SmmServer/SmmServer/files/3832835/Caddy.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3832836/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3832837/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/3832840/Pretendo%2B%2B.log)

I left the MLC path blank. Could you also be more specific on how I configured Cemu?

**Comment by mrexodia** [comment]
Hm looking at the logs it doesn't make too much sense. You are missing a lot of the startup calls and it appears that there are different difficulty parameters being sent for 100 mario. Could you record your screen where you install and start SmmServer from scratch?

**Comment by MiiCordYT** [comment]
https://youtu.be/ecj9WcIgGPw

The sped-up part at the end is just me unlocking the main menu.
As for the Main Game/Update, I got them by selecting EUR in The Wii U Usb helper and by downloading the game and the update files. At least I think I got the update considering once I insert it with cemu, it reads V272.

**Comment by mrexodia** [comment]
There is something very strange going on, the SmmServer UI is supposed to show newlines between the log messages, but it's not really showing that... Otherwise the weird thing is that your course parameters appear to be different from other users and I have no idea why.

Could you try replacing `NintendoClients\example_smm_server.py` with [this version](https://github.com/SmmServer/NintendoClients/blob/fce1bfda726ef519cb91ac197566dae9358fc122/example_smm_server.py) and report back? Be sure to download the file (right click on `Raw` -> save as) and not copy paste the contents.

**Comment by MiiCordYT** [comment]
Now I'm getting an Error-Code: 106-0103 

[Caddy.log](https://github.com/SmmServer/SmmServer/files/3833419/Caddy.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3833420/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3833421/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/3833422/Pretendo%2B%2B.log)

**Comment by mrexodia** [comment]
The logs show nothing of interest here. Could you make sure to close SmmServer before sending the logs?

**Comment by MiiCordYT** [comment]
New Logs:
[Caddy.log](https://github.com/SmmServer/SmmServer/files/3838224/Caddy.log)
[NEX (Friends).log](https://github.com/SmmServer/SmmServer/files/3838225/NEX.Friends.log)
[NEX (SMM).log](https://github.com/SmmServer/SmmServer/files/3838226/NEX.SMM.log)
[Pretendo++.log](https://github.com/SmmServer/SmmServer/files/3838227/Pretendo%2B%2B.log)

Do you know what Error Code 106-0103 means?

**Comment by MiiCordYT** [comment]
Is there anything else you need to know from me?

**Comment by mrexodia** [comment]
No, I investigated more but my only conclusion is that something weird is going on. You can try not using your existing game library and getting a fresh copy of the game+update, but otherwise I have no idea. Your version of the game is sending completely alien packets, my current theory is that somehow it is sending packets for the old server version, but nothing conclusive.

I also tried the latest USA version of the game and it also works, so no ideas otherwise...

**Comment by MiiCordYT** [comment]
Thanks for everything you could do to help me!!
